AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation